[app]
name = "Stock Trading System"
port = 8081
env = "development"
log_level = "debug"
market_update_interval = "1m"

[db]
host = "localhost"
port = 5432
user = "postgres"
password = "root"
name = "stock_trading"

[redis]
host = "localhost"
port = 6379
password = ""

[jwt]
secret = "supersecretkeychangeinprod"
expiration_hours = 24
